# Generated by Django 5.2.5 on 2025-09-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveBigIntegerField()),
                ('descripcion', models.TextField(null=True)),
                ('foto', models.ImageField(null=True, upload_to='productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productApp.marca')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
