# Generated by Django 5.2.5 on 2025-09-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
