# Generated by Django 5.2.5 on 2025-09-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_remove_producto_id_alter_producto_codigo'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para hacer codigo autoincremental
            "ALTER TABLE productos MODIFY COLUMN codigo INT AUTO_INCREMENT PRIMARY KEY;",
            # SQL para revertir (si es necesario)
            "ALTER TABLE productos MODIFY COLUMN codigo INT;"
        ),
    ]
